services:
  highlight:
    # image: ghcr.io/zomatree/highlight
    build: .
    volumes:
      - ./Highlight.toml:/Highlight.toml:ro
    environment:
      RUST_LOG: error
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:18
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d highlight -U highlight"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: highlight
      POSTGRES_PASSWORD: password
      POSTGRES_DB: highlight

volumes:
  pgdata: